#!/usr/bin/env python3
"""Generate src/data/extraDocs.ts from 'Additional Darwin bits' — a mix of
Darwin practice-specific admin docs (source: 'darwin') and general resources."""
import os, re, collections
from urllib.parse import quote
try:
    import fitz
except ImportError:
    fitz = None

ROOT = "public/pdfs/Additional Darwin bits"
OUT_TS = "src/data/extraDocs.ts"

# filename → (title, category, source)   source '' = general resource
META = {
    'Admin allocation to Drs.pdf':                       ('Admin Allocation to Doctors', 'Practice', 'darwin'),
    'Catchment Map.pdf':                                 ('Practice Catchment Map', 'Practice', 'darwin'),
    'Darwin Pathology Protocols at 18th August 2026.pdf':('Darwin Pathology Protocols', 'Practice', 'darwin'),
    'Housebound Oct 25.pdf':                             ('Housebound Patients List (Oct 2025)', 'Practice', 'darwin'),
    'Food first recipe sheets.pdf':                      ('Food First Recipe Sheets', 'Gastro', ''),
    'Primary Care Quick Guide to ONS.pdf':               ('Primary Care Quick Guide to ONS', 'Gastro', ''),
}
# extra search synonyms per file
KW = {
    'Food first recipe sheets.pdf': 'ons oral nutritional supplement malnutrition weight loss fortify food first recipe calorie',
    'Primary Care Quick Guide to ONS.pdf': 'ons oral nutritional supplement prescribing malnutrition must score fortisip ensure aymes complan sip feed',
    'Admin allocation to Drs.pdf': 'admin workflow allocation doctors tasks practice',
    'Catchment Map.pdf': 'catchment boundary area postcode practice map registration',
    'Darwin Pathology Protocols at 18th August 2026.pdf': 'pathology protocol blood test result abnormal darwin practice',
    'Housebound Oct 25.pdf': 'housebound visit list patients home',
}
STOP = set("the a an and or of to in for with on at by is are be this that from as it its into your you we our will can may not have has had if then than".split())
GENERIC = {'patient','form','name','date','please','address','details','service','nhs','practice',
           'number','information','tel','email','darwin','page'}

def body_keywords(path):
    if not fitz: return ''
    try:
        d = fitz.open(path); txt = ' '.join(p.get_text() for p in d); d.close()
    except Exception:
        return ''
    words = re.findall(r"[A-Za-z][A-Za-z\-']{3,}", txt)
    freq = collections.Counter()
    for w in words:
        wl = w.lower()
        if wl in STOP or wl in GENERIC: continue
        freq[wl] += 1
    return ' '.join(w for w, _ in freq.most_common(30))

def slug(s): return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')[:70]

records = []
for fn in sorted(os.listdir(ROOT)):
    if not fn.lower().endswith('.pdf'): continue
    title, category, source = META.get(fn, (fn[:-4].title(), 'Practice', 'darwin'))
    kw = set(KW.get(fn, '').split()) | set(body_keywords(os.path.join(ROOT, fn)).split())
    kw |= set(re.sub(r'[^a-z0-9 ]', ' ', title.lower()).split())
    keywords = ' '.join(sorted(x for x in kw if x and x not in STOP))
    rid = ('darwin-' if source == 'darwin' else 'extra-') + slug(title)
    url = 'pdfs/' + quote('Additional Darwin bits/' + fn)
    records.append((rid, title, category, source, url, keywords))

def ts(s): return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
lines = ['// AUTO-GENERATED by scripts/gen_extras.py — do not edit by hand.',
         '// Extra library docs: Darwin practice admin (source: darwin) + general resources.',
         '', "import type { GPForm } from './forms'", '',
         'export const EXTRA_DOCS: GPForm[] = [']
for rid, title, category, source, url, keywords in records:
    src = f", source: 'darwin'" if source == 'darwin' else ''
    lines.append(f"  {{ id: {ts(rid)}, title: {ts(title)}, category: {ts(category)}{src}, url: {ts(url)}, keywords: {ts(keywords)} }},")
lines.append(']')
open(OUT_TS, 'w').write('\n'.join(lines) + '\n')
print(f"Wrote {len(records)} extra docs to {OUT_TS}")
for r in records: print(f"  [{r[3] or 'general':7}] [{r[2]:9}] {r[1]}")
