import type { Note } from '../data/notes'

export const darwinReferrals: Note = {
  id: 'darwin-referrals',
  title: 'Darwin Practice — Referral Guide',
  subtitle: 'Where & how to refer at Darwin Medical Practice (Burton/Lichfield)',
  tags: ['admin', 'local', 'darwin', 'referrals'],

  body: `Darwin practice referral guide where how to refer Burton Lichfield UHDB MPFT lexacom secretaries 2WW two week wait cancer urgent referral ADHD ASD CAMHS CaFSPA MSK orthopaedic physiotherapy mental health memory dementia MHSI district nurse community matron continence radiology ICE imaging MRI CT USS ultrasound echo ECG DVT TIA chest pain rapid access eating disorders fertility infertility audiology dermatology teledermatology neurology cardiology respiratory diabetes endoscopy podiatry social prescribing palliative hospice St Giles weight management bariatric Wellbeing Matters alcohol STARS safeguarding falls fracture pain management ERS e-referral Accumail Lexacom admin secretary Jo Nicky Alison Lindsey`,

  content: [
    // ── PROCESS ───────────────────────────────────────────────────────────────
    {
      type: 'callout',
      variant: 'info',
      title: 'How to Send Referrals at Darwin',
      items: [
        'Use **Lexacom** for all referrals where possible — dictate or autopopulate EMIS forms',
        '2WW referrals: mark as **IMMEDIATE** priority on Lexacom',
        'Forms with email address → send via **Accumail** (@ tab in Accurx toolbar)',
        'No Lexacom in room → type referral, send via **PATIENT task** to Secretarial Team',
        'Secretaries: Alison ext 2215 (Lichfield), Lindsey ext 2216 (Lichfield), Jo ext 3365 (Greenwood Mon/Tue/Wed), Nicky ext 3366 (Greenwood Mon-Thu)',
        'Practice email: darwinmedical.practice@nhs.net | Secretaries: darwin.secretaries@nhs.net',
        'Default hospital: **Queen\'s Hospital Burton (UHDB)** | MH: **MPFT 0300 555 5001** | CAMHS: **CaFSPA**',
      ],
    },

    // ── A-Z REFERRAL TABLE ────────────────────────────────────────────────────
    {
      type: 'heading',
      level: 2,
      text: 'A–Z Referral Destinations',
    },
    {
      type: 'table',
      headers: ['Condition / Service', 'Where / How', 'Key Details'],
      rows: [
        ['AAA Surveillance', 'Derby — email dhft.AAAscreening@nhs.net', 'After aneurysm found, routine surveillance'],
        ['ADHD Child (NHS)', 'Age 6–10 → Community Paeds | Age 11–18 → CAMHS', 'Use Neurodevelopmental form (school to complete)'],
        ['ADHD Adult (NHS)', 'MPFT — integrated form on EMIS', 'No ASRS required; they will screen; include MH history + risk'],
        ['ADHD Adult (RTC)', 'ICB portal — patient completes Form A/B (PRF020), GP completes Form C (PRF021)', 'Secretaries upload both forms to portal'],
        ['ASD Child (NHS)', 'CYP Autism team — Neurodevelopmental form | Under 5 → Community Paediatrics', 'School should refer; send Accurx info sheet to parent'],
        ['ASD Adult (NHS)', 'MPFT — integrated form on EMIS', 'No AQ50 required; they will screen; include MH history + risk'],
        ['Alcohol/Drug', 'STARS — self-referral only (Accurx link to patient)', 'Need email address; give patient all contact/communication details'],
        ['Allergy (skin prick)', 'Lung Function form → Cannock Respiratory Bookings Team (via Accumail)', 'Service suspended as of Jan 2024; check if resumed'],
        ['Anticoagulation', 'In-house (Ros Needham). Secondary: Derby ERS — Haematology/Anticoag/Warfarin', 'Telephone clinic only for QHB anticoag'],
        ['Audiology (adult)', 'Self-referral via ICB form (Specsavers etc) or GP referral via ERS', 'Ears must be clear of wax. Housebound → email specsavershearing.tamworth@nhs.net'],
        ['Audiology (child)', 'Community Audiology, The Coach House, Lichfield (letter/email)', 'Include school details'],
        ['Bariatric surgery', 'Adult Dietetics first; then Manor Hospital (if sufficient work-up)', 'Note: Manor currently not accepting (Feb 2026); refer to Adult Dietetics only'],
        ['Breast (routine/urgent)', 'ERS — Derby manages booking; patients seen at Burton Breast Unit', 'ALL breast referrals seen within 2 weeks; patient must be available. Derby form for Burton 2WW breast'],
        ['Breast Pain only', 'Community Breast Pain Clinic — Samuel Johnson or Sir Robert Peel (ERS)', 'Breast pain only, no other symptoms AT ALL; no implants/male/Ca history; try NSAID, bra, diary first'],
        ['CAMHS', 'Form on EMIS → email via CaFSPA → Holly Lodge, St Michael\'s Court', 'Include school; ADHD via Neurodevelopmental form not CAMHS form'],
        ['Cataract', 'ERS — can refer to Cannock/Manor/Good Hope/New Cross/Burton (not SRP/SJH)', 'Must be referred via accredited optician'],
        ['CFS (Chronic Fatigue)', 'Derby Hospital — EMIS form (Derby postcode). Alt: Cannock (diagnosed CFS only)', 'Bloods required: FBC, ESR, CRP, U&E, LFT, Ca, HbA1c, TFT, Coeliac, CK, Ferritin, Vit D'],
        ['CAMHS Eating Disorders (8–18)', 'EMIS form → email. Include height/weight/BP standing+sitting/bloods/ECG/patient questionnaire', ''],
        ['Eating Disorders Adult (>18)', 'Letter to Adult Eating Disorder Service, St Chad\'s House, St George\'s Hospital, Stafford ST16 3AG | Tel: 01785 783120', ''],
        ['Cardiac Rehab/Heart Failure', 'Stoneydelph Health Centre (Tamworth) — Phase II via consultant only', 'Tel: Rebecca Jackson 01827 306115 | southHFSN@mpft.nhs.uk'],
        ['Cardiorespiratory (Echo/24BP/Home ECG)', 'Burton — EMIS Diagnostics form → Accumail to Burton Referrals', 'For cardiology review (not just technical report) → ERS into Cardiology'],
        ['Chest Pain (rapid access)', 'ERS — Burton or Good Hope via integrated EMIS form', 'Organise bloods/ECG/medication on form; give patient copy of ECG'],
        ['Chronic Pain Management', 'MPFT Edwin House, Burton — EMIS form → ERS or email cpms.admin@mpft.nhs.uk | Tel: 01283 507131', 'Over 18 only; physio first; >3–6 months severe symptoms; not palliative/cancer-related pain'],
        ['Colposcopy', 'ERS — Gynaecology/NOS | SRP or Burton', ''],
        ['Community Paediatrics', 'MPFT East Community Paeds — EMIS form | Email: MPFT.Paedsreferrals@nhs.net | Tel: 01283 505160', 'Include school details; check exclusions (no ASD >5, no behavioural issues, no obesity, no tics)'],
        ['Continence/Pelvic Health', 'Specialist Pelvic Health Team — EMIS form → email mpft.spht@nhs.net | Tel: 01543 441434', 'Rule out UTI first; include MSU date/result; 40-week routine wait'],
        ['Counselling/Wellbeing Matters', 'Self-referral — give patient leaflet (create document in EMIS: "Self referral to Wellbeing service given")', ''],
        ['Community Matron', 'EMIS integrated WEB form → email SPA sst-tr.bltspa@nhs.net | Emergency: 07772944024', 'Send urgent Lexacom/task after completing form'],
        ['Dementia/Memory', 'MHSI Hub — EMIS integrated form | Tel: 0300 555 5001', 'Pre-referral: GPCOG/6CIT + bloods (B12, Folate, FBC, LFT, U&E, TFT, Lipids, HbA1c, Calcium, eGFR)'],
        ['Dermatology (adult/paed)', 'Health Harmonie (community) — A&G via ERS. Paed: A&G on ERS to Burton first (from 1.10.23)', 'No benign lesions/warts/verruca (PoLCV). No under 16 for surgical procedures. Teledermatology via Consultant Connect app'],
        ['DEXA Scan', 'Cannock: search DXA → RF758 RWT DXA Scan Referral (controlled doc; do not modify; email). Burton: radiology DEXA form on EMIS', ''],
        ['Diabetes Clinic', 'MPFT Primary Care Specialist Diabetes Team → EMIS form → email | QHB: bhft.diabetescentre@nhs.net (urgent: 01283 593113 opt 2)', ''],
        ['Dietician (adult >18)', 'MPFT Adult Specialist Dietetics, Beecroft Court Cannock — EMIS integrated WEB form', 'Weight management: see W'],
        ['Dietician (child <18)', 'Sir Robert Peel Hospital Dietetics | Email: childrensdiet@mpft.nhs.uk | Tel: 01827 263800 ext 8240', 'Weight management <18: Time4Sport, Stoke'],
        ['District Nurses', 'EMIS integrated WEB form → Accumail | Email: sst-tr.bltspa@nhs.net', ''],
        ['DVT', 'Wells score first → Burton USS 01283 511511 ext 4201 or Good Hope 0121 4247158', 'Wells ≥2 OR <2 + positive D-dimer → arrange proximal leg vein USS. If wait >4h → interim parenteral anticoag'],
        ['ECG', 'In-house (task to reception). Home ECG/24hr or 7-day → Burton EMIS Diagnostics form → Accumail. 72hr → Cannock EMIS form (patient books)'],
        ['Endoscopy', 'Service currently suspended post-COVID — refer to consultant for triage', ''],
        ['ENT (urgent)', 'Phone Burton 01283 566333 → ask for QHB ENT on-call to discuss', 'They arrange ENT CAS clinic if needed'],
        ['Eye Casualty', 'Email bhft.eyecas@nhs.net (ext 5085/6364) or ERS urgent triage to New Cross | CUES: 0333 015 0122 (Mon–Sat 9–5)', ''],
        ['Falls', 'EMIS integrated WEB form → Lexacom/email | Falls Team, Tamworth', ''],
        ['Fertility / Infertility', 'Nurture Fertility, Burton (referral in female name). Male: sperm test at QHB first', 'Female bloods: regular cycle → Day 1–5 FSH/LH, mid-luteal prog, Chlamydia, Rubella. Irregular → add TSH, prolactin. Advise Folic Acid, smoking, alcohol, BMI'],
        ['Fracture Clinic', 'ERS — Orthopaedics (choose body part) → triage to correct consultant', ''],
        ['Gender Dysphoria/Transgender', 'Nottingham Centre for Transgender Health — integrated EMIS form | Email: ReferralsNCTH@nottshc.nhs.uk | Under 17 → CAMHS first', 'Up to 2+ year wait'],
        ['Gynae (Good Hope)', 'Advice & Guidance pathway only — tick box to allow conversion to referral', ''],
        ['Gynaecology (physio)', 'Continence/Pelvic Health Team form (tick physio box); rule out MSU first', ''],
        ['Home Oxygen', 'Baywater Healthcare online portal: baywater.co.uk | Tel: 0800 373580', 'Emailed HOOFs no longer accepted'],
        ['Hydrotherapy (Cannock)', 'Letter → email RWH-tr.MSKphysio@nhs.net', 'Not guaranteed; rejected if not appropriate'],
        ['Immunology', 'Birmingham Treatment Centre / Heartlands / County Hospital Stafford', 'No longer Burton (going to Stoke)'],
        ['Iron Transfusion', 'GP refers direct to SDEC at QHB', 'Dose: Ferinject 1000mg then 500mg 1 week later; only if poor compliance/intolerance/malabsorption to oral iron'],
        ['Learning Disability (adult)', 'MPFT Friary Centre, St Michael\'s Court — email CLDTEast@mpft.nhs.uk', 'Adults diagnosed with LD as children only; ASD adult assessment → neurodevelopmental.service@nhs.net (Dudley & Walsall MHT)'],
        ['Learning Disability (child)', 'Children\'s LD Team, The Friary, Lichfield | Tel: 0300 790 7000 ext 7021512 | childrensld.team@nhs.net', ''],
        ['Lumps & Bumps', 'ERS — most local hospitals; check ICB PoLCV for benign cysts etc', 'Hernias also via ERS'],
        ['Lymphoedema', 'St Giles — EMIS form → Accumail direct | Include: site of swelling, duration, pain type, cardiac/renal status, DVT excluded', 'BMI >30: weight management referral needed; >40: specialist bariatric referral needed first'],
        ['Maxillofacial', 'Letter → base hospital via ERS', ''],
        ['Mental Health (adult)', 'MHSI Hub — EMIS integrated WEB form | Email via secretaries | Tel: 0300 555 5001 opt 2 (Block 6, St Michael\'s Court, Lichfield)', ''],
        ['MRI', 'ICE → Burton (adult). Cannock mobile MRI for 19+ (no contrast, no under 19, weight limit 23 stone, has steps). Children → QHB. Babies (sedation needed) → Burton only', ''],
        ['MS Nurse', 'Amanda Taylor, Samuel Johnson → OT/Rehab form → LAP email | Cannock: rwh-tr.msnurses@nhs.net', ''],
        ['MSK / Orthopaedics / Physio', 'ALL orthopaedic referrals (>18): MSK form on EMIS (March 2025) → task to Team Leaders TB & AB', 'Under 18 → Paed Physio. Podiatric surgery (hallux valgus, hammer toes) → MSK not Podiatry'],
        ['Nerve Conduction/Carpal Tunnel', 'Cannock hand/carpal tunnel clinic via ERS or letter to Consultant Neurophysiologist at QHB', ''],
        ['Neurology', 'No neurology at Burton. Cannock (MS/Parkinson\'s/Bell\'s/migraine/epilepsy etc). Robert Peel (general, NOT epilepsy). Manor/County (general). Good Hope via A&G first (not benign headache/dizziness/vertigo)', ''],
        ['Occupational Therapy', 'EMIS integrated form → email LAP. Long-term care → ILCT via SPA. If no care package → ring Staffordshire Cares 0300 111 8010', ''],
        ['Orthotics', 'Samuel Johnson — EMIS form → email opcare.burtonorthotics@nhs.net', 'Includes surgical belts, insoles'],
        ['Paediatric Physio', 'Beecroft Court, Cannock — EMIS WEB form → email', 'Check advice on form about unnecessary referrals (flat feet, intoeing gait, talipes)'],
        ['Palliative / St Giles Hospice', 'Online referral via St Giles website "How Can We Help" (as of 1 June 2025)', 'No Word forms available; must use their online portal'],
        ['Parkinson\'s Nurse', 'Karen Wrotchford, Samuel Johnson — OT/Rehab form → LAP | Tel: 01543 728142', ''],
        ['Perinatal Mental Health', 'MPFT — EMIS form → email perinatal.communityteam@mpft.nhs.uk', ''],
        ['Plastic Surgery', 'Check ICB PoLCV guidelines strictly before any aesthetic referral', ''],
        ['Podiatry', 'EMIS WEB integrated form → email (Appt Booking Centre). Diabetic Podiatry: normal form, FAO Advanced Diabetes Podiatrist', 'Podiatric surgery (hallux valgus, hammer toes, claw toes) → MSK team'],
        ['Radiology (general)', 'ICE online test request (preferred). Paper signed forms if not on ICE catalogue', 'X-Ray exclusions: no routine lumbar spine XR for back pain/sciatica; Calcaneal spur XR only by specialist'],
        ['Radiology USS exclusions', 'No direct USS for: breast/axilla (→ Breast Clinic), groin/hernias (→ Consultant), Morton\'s Neuroma (treat first). Health Harmonie exclusions: breast, cardiac, chest, obstetric, under 18', ''],
        ['Rapid Access Chest Pain', 'ERS — Burton or Good Hope via EMIS integrated form', ''],
        ['ReSPECT Form', 'Integrated on EMIS', ''],
        ['Safeguarding (children)', 'First Response Team: 0800 1313 126 | online reporting via Staffordshire.gov.uk', 'Clinician to call in first instance'],
        ['Safeguarding (adults)', 'Staffordshire County Council: 0345 604 2719 | Out of hours: 0345 604 2886', ''],
        ['Social Prescribing', 'EMIS Social Prescribing form → email Jessica.ryan@staffs.nhs.uk (Link Worker)', ''],
        ['Spirometry', 'Langton MC Lichfield — EMIS DAR-Spirometry form → Lexacom/task team leads to book | Cannock Hospital: GP direct access (18+ only)', ''],
        ['Stoma Care', 'Kerry Shakespeare, Burton | Email: kerry.shakespeare@securicaremedical.co.uk | Tel: 01283566333 ext 2122', 'Patient self-referral to Amcare: 0800 88 50 50'],
        ['Stroke Team', 'Community Stroke Team, Stoneydelph Health Centre — OT/Rehab form on EMIS | Tel: 01827 891069', ''],
        ['TIA Clinic', 'ERS — Burton or Good Hope via integrated EMIS forms', ''],
        ['Termination of Pregnancy', 'Patient self-refers to NUPAS: 0333 004 666 (7 days, 8am–8pm)', 'No GP referral needed'],
        ['Tissue Viability', 'Mobile patients → Ambulatory form → SPA | Housebound → District Nurses first', 'Email: tissue.viability7@nhs.net | Tel: 01889 571435 (for advice)'],
        ['Ultrasound (community)', 'Health Harmonie via ERS — EMIS form → secretaries (select Tamworth option)', 'Exclusions: breast, axilla, cardiac, chest, obstetric, ophthalmology'],
        ['Vascular / Varicose Veins', 'Letter → base hospital. VV surgery: must meet ICB PoLCV criteria (bled, ulcerated, phlebitis, significant CVI)', ''],
        ['Vasectomy', 'ERS — Brewood Medical Services (AQP). Counsel patient and document in letter', ''],
        ['Weight Management', 'NHS Digital Weight Management (BMI ≥30 + DM/hypertension, digital access). Everyone Health self-referral (BMI ≥28+LTC or ≥30). Bariatric: Adult Dietetics first', 'Mounjaro (tirzepatide) from June 2025: BMI ≥40 + ≥4 comorbidities only'],
        ['Wheelchair', 'AJM Wheelchair Services — EMIS form | Tel: 0808 175 3996 | AJM.ssotwheelchairservice@nhs.net', ''],
      ],
    },

    // ── 2WW ──────────────────────────────────────────────────────────────────
    {
      type: 'heading',
      level: 2,
      text: '2 Week Wait (2WW) Referrals',
    },
    {
      type: 'callout',
      variant: 'warning',
      title: '2WW Process',
      items: [
        'Access forms via EMIS: Document → Create Letter → 2WW Referrals folder → usually Queen\'s Hospital Burton',
        'Breast 2WW: use Derby form (patients still seen at Burton)',
        'No Brain/CNS service at Burton — refer to New Cross or Stoke (UHNM)',
        'Burton: does NOT accept under 25\'s (except Dermatology and Breast)',
        'After completing form: send Lexacom marked **IMMEDIATE** → specialty "2WW"',
        'Tell patient: contact us after **1 week** if no communication',
        'Child dermatology 2WW: email form to bcw.appointments@nhs.net',
        'Derm 2WW (WHT/RWT): use Health Harmonie form — state lesion site, size, number',
        'FIT test required before colorectal 2WW for change in bowel habit / rectal bleeding / unexplained weight loss / abdo pain (request via ICE online test request → UHDB)',
        'Temporary residents: cannot refer via ERS',
      ],
    },

    // ── RADIOLOGY QUICK REF ───────────────────────────────────────────────────
    {
      type: 'heading',
      level: 2,
      text: 'Radiology Quick Reference',
    },
    {
      type: 'table',
      headers: ['Scan', 'Where', 'How'],
      rows: [
        ['X-Ray', 'Burton (SJH)', 'ICE preferred; signed paper forms if not on catalogue'],
        ['CT', 'Burton (QHB)', 'ICE; open scanner available at QHB — state on form'],
        ['MRI', 'Burton (QHB) or Cannock mobile (19+, no contrast, steps)', 'ICE → Burton; Cannock via separate EMIS integrated form → email'],
        ['Cannock MRI', 'Diagnostic Healthcare mobile unit, Cannock car park', 'No under 19, no contrast, weight limit, steps — send via ERS'],
        ['USS', 'Health Harmonie (community) or Burton', 'Health Harmonie via ERS (Tamworth option); Burton USS form → Accumail'],
        ['Echo', 'Burton — EMIS Diagnostics form → Accumail', 'Cardiology review (not just technical) → ERS into Cardiology separately'],
        ['DEXA', 'Cannock: RF758 form (do not modify) → email. Burton: DEXA form on EMIS', ''],
        ['Spirometry', 'Langton MC Lichfield or Cannock Hospital (18+ only)', 'EMIS form → Lexacom to secretaries'],
      ],
    },

    // ── INFERTILITY ───────────────────────────────────────────────────────────
    {
      type: 'heading',
      level: 2,
      text: 'Infertility Pre-referral Checklist',
    },
    {
      type: 'table',
      headers: ['Check', 'Regular cycle', 'Irregular cycle'],
      rows: [
        ['FSH & LH', 'Day 1–5', 'Random'],
        ['Progesterone', 'Mid-luteal (7 days pre-onset)', '—'],
        ['TSH & Prolactin', '—', 'Required'],
        ['Chlamydia', 'Required (last 6 months)', 'Required (last 6 months)'],
        ['Rubella', 'Required (last 5 years)', 'Required (last 5 years)'],
      ],
      caption: 'Male: sperm test at QHB within 12 months (form PRF769). Advise folic acid, smoking cessation, alcohol, BMI <30 (F) / <35 (M)',
    },
  ],
}
